"""One-off generator of strategy/members/k5/_calendar.py (Stage E.4 Part 2, MemberCoder-A).

Not imported by anything. Run from the repository root:

    uv run python reports/stage_e4_briefs/gen_k5_calendar.py

It reads EC-CAL, the D10 metals calendar, through data.group_session.load_group_calendar("metals")
and writes METALS_FULL_SESSIONS (reports/stage_e4b_member_specs.md S0.11; used by K5-ovr-01's
reference dates, K5-L-05):

- every EC-CAL metals trade date over the calendar's own coverage, 2019-05-01..2026-06-19
  (data.group_session.trade_dates_between, i.e. GroupCalendar.is_trade_date: a weekday that is not
  a FULL_CLOSURE holiday and not a booked-forward day)
- whose GroupCalendar.early_halt_ct is None (no early halt).

The range is EC-CAL's own coverage (K4-L-13, adopted for K5 in reports/stage_e4b_member_specs.md
section 10): outside it the calendar says nothing, so no date there is listed.

tests/test_e4_k5_members_a.py recomputes the table from the calendar and asserts equality with the
written module (the pin), so the file and this script cannot drift apart silently.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from data.group_session import (  # noqa: E402
    load_group_calendar,
    sha256_file,
    trade_dates_between,
)

OUT = REPO_ROOT / "strategy" / "members" / "k5" / "_calendar.py"
CALENDAR_FILE = "data/calendars/metals.py"
FIRST = date(2019, 5, 1)  # EC-CAL coverage start (K4-L-13)
LAST = date(2026, 6, 19)  # EC-CAL coverage end (K4-L-13)
PER_LINE = 5


def full_sessions() -> list[str]:
    """ISO dates of every metals trade date FIRST..LAST with no early halt, oldest first."""
    cal = load_group_calendar("metals")
    assert (FIRST, LAST) == tuple(cal.coverage), (FIRST, LAST, cal.coverage)  # K4-L-13
    return [d.isoformat() for d in trade_dates_between(cal, FIRST, LAST)
            if cal.early_halt_ct(d) is None]


def render(days: list[str], sha: str) -> str:
    lines = []
    for i in range(0, len(days), PER_LINE):
        lines.append("    " + " ".join(f'"{d}",' for d in days[i:i + PER_LINE]))
    body = "\n".join(lines)
    return f'''"""EC-CAL metals full sessions (literal table; S0.11, K5-L-05).

GENERATED by reports/stage_e4_briefs/gen_k5_calendar.py from EC-CAL, the D10 metals calendar
({CALENDAR_FILE}, read through data.group_session.load_group_calendar("metals")).
Do not edit by hand: tests/test_e4_k5_members_a.py recomputes the table from the calendar and
asserts equality.

METALS_FULL_SESSIONS = every metals trade date {FIRST.isoformat()}..{LAST.isoformat()} (GroupCalendar.is_trade_date:
a weekday that is not a FULL_CLOSURE holiday and not a booked-forward day) whose early_halt_ct is
None. Used by K5-ovr-01 (its 20 reference dates, K5-L-05).
The range is EC-CAL's coverage (K4-L-13): no date outside it is listed.
"""

from __future__ import annotations

METALS_FULL_SESSIONS_SOURCE = (
    "EC-CAL: data.group_session.load_group_calendar('metals') ({CALENDAR_FILE}); "
    "trade_dates_between({FIRST.isoformat()}, {LAST.isoformat()}) with early_halt_ct None"
)
# sha256 of {CALENDAR_FILE} when the table was generated
METALS_FULL_SESSIONS_SOURCE_SHA256 = "{sha}"

# ISO dates, oldest first ({len(days)} dates)
METALS_FULL_SESSIONS: tuple[str, ...] = (
{body}
)
'''


def main() -> None:
    days = full_sessions()
    sha = sha256_file(REPO_ROOT / CALENDAR_FILE)
    OUT.write_text(render(days, sha), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}: {len(days)} dates {days[0]}..{days[-1]}, "
          f"source sha256 {sha[:12]}")


if __name__ == "__main__":
    main()
