"""K6-limitcont-01's limit tables (literal;
reports/stage_e8_member_specs.md S0.11, section 5, K6-L-06, K6-L-07, K6-L-08 and section 10
rulings R-1b-2, R-1b-3).

GENERATED by reports/stage_e8_briefs/gen_k6_tables.py from rules.price_limits (LIMITS and
SETTLEMENT_WINDOW_CT; rules/price_limits.py sha256 below) and Task 1b's check. Do not edit by
hand: tests/test_k6_members_tables.py recomputes the tables and asserts this file is the
generator's output.

- LIMIT_PERIODS: root -> (first trade date, last trade date, initial daily limit in USD per pound
  as the exact decimal string LIMITS writes) for every HARD_DAILY period of HE and LE intersecting
  2019-05-01..2026-06-19; each period's status (sourced / bracketed / carried) is its comment.
  Only the initial limit is encoded (flag R-L2, K6-L-07). The member converts an amount to vendor
  ticks as amount x vendor_price_factor / vendor_tick, an integer for every period.
- SETTLEMENT_WINDOW_LIVESTOCK: rules.price_limits.SETTLEMENT_WINDOW_CT["livestock"], [start, end)
  CT, the D9.7 proxy window of a regular livestock day (K6-L-06).
- DROPPED_LIMIT_DATES: root -> {trade date: reason}; the member does not trade a d whose event
  test reads L on a dropped date (d-1 or d-2). R-1b-2: the 14 LE trade dates 2026-06-01..06-18.
  HE: none.
"""

from __future__ import annotations

from datetime import date, time

# sha256 of the sources when the tables were generated
SOURCE_SHA256: tuple[tuple[str, str], ...] = (
    ("rules/price_limits.py",
     "b9031e133528368466861d0f8323adb732f9e064be090a57ab0d4095dbd3b6b8"),
    ("reports/stage_e8_release_check.json",
     "99547c142110cb5d4f6cf519ed488c98a5b78c4836d667dc292fe028d8f95c6b"),
)

LIMIT_RANGE = ("2019-05-01", "2026-06-19")

LIMIT_PERIODS: dict[str, tuple[tuple[date, date, str], ...]] = {
    "HE": (
        (date(2019, 5, 1), date(2020, 4, 1), "0.03"),  # sourced
        (date(2020, 4, 2), date(2020, 4, 21), "0.03"),  # bracketed
        (date(2020, 4, 22), date(2020, 8, 19), "0.0375"),  # sourced
        (date(2020, 8, 20), date(2020, 9, 21), "0.03"),  # bracketed
        (date(2020, 9, 22), date(2021, 8, 31), "0.03"),  # sourced
        (date(2021, 9, 1), date(2023, 8, 31), "0.0475"),  # sourced
        (date(2023, 9, 1), date(2024, 9, 3), "0.0375"),  # sourced
        (date(2024, 9, 4), date(2024, 9, 12), "0.0375"),  # bracketed
        (date(2024, 9, 13), date(2025, 8, 29), "0.0400"),  # sourced
        (date(2025, 8, 30), date(2025, 9, 1), "0.0400"),  # bracketed
        (date(2025, 9, 2), date(2026, 6, 19), "0.0475"),  # sourced
    ),
    "LE": (
        (date(2019, 5, 1), date(2020, 10, 4), "0.03"),  # sourced
        (date(2020, 10, 5), date(2021, 5, 31), "0.04"),  # sourced
        (date(2021, 6, 1), date(2022, 5, 31), "0.05"),  # sourced
        (date(2022, 6, 1), date(2023, 5, 31), "0.0575"),  # sourced
        (date(2023, 6, 1), date(2024, 6, 2), "0.0675"),  # sourced
        (date(2024, 6, 3), date(2024, 10, 8), "0.0750"),  # sourced
        (date(2024, 10, 9), date(2024, 11, 5), "0.0650"),  # bracketed
        (date(2024, 11, 6), date(2025, 6, 1), "0.0650"),  # sourced
        (date(2025, 6, 2), date(2026, 5, 18), "0.0725"),  # sourced
        (date(2026, 5, 19), date(2026, 6, 19), "0.0725"),  # bracketed
    ),
}

# rules.price_limits.SETTLEMENT_WINDOW_CT["livestock"]: [start, end) CT
SETTLEMENT_WINDOW_LIVESTOCK: tuple[time, time] = (time(12, 59, 30), time(13, 0))

# R-1b-2 (spec section 10, lead 00:32 PDT; Task 1b B1/B2: the period LE 2026-05-19..2026-06-19
# verdict drop)
_LE_DROP_REASON = (
    "R-1b-2: CME SER-9736 (May 14, 2026) sets a new initial Live Cattle limit of $0.0850 "
    "effective trade date 2026-06-01; the frozen table (bracketed 2026-05-19..2026-06-19)"
    " holds $0.0725")
DROPPED_LIMIT_DATES: dict[str, dict[date, str]] = {
    "HE": {},  # R-1b-2 / R-1b-3: no dropped HE date
    "LE": {
        date(2026, 6, 1): _LE_DROP_REASON,
        date(2026, 6, 2): _LE_DROP_REASON,
        date(2026, 6, 3): _LE_DROP_REASON,
        date(2026, 6, 4): _LE_DROP_REASON,
        date(2026, 6, 5): _LE_DROP_REASON,
        date(2026, 6, 8): _LE_DROP_REASON,
        date(2026, 6, 9): _LE_DROP_REASON,
        date(2026, 6, 10): _LE_DROP_REASON,
        date(2026, 6, 11): _LE_DROP_REASON,
        date(2026, 6, 12): _LE_DROP_REASON,
        date(2026, 6, 15): _LE_DROP_REASON,
        date(2026, 6, 16): _LE_DROP_REASON,
        date(2026, 6, 17): _LE_DROP_REASON,
        date(2026, 6, 18): _LE_DROP_REASON,
    },
}

__all__ = ["DROPPED_LIMIT_DATES", "LIMIT_PERIODS", "SETTLEMENT_WINDOW_LIVESTOCK"]
