"""K6 EC-WASDE table (literal; reports/stage_e8_member_specs.md S0.11,
K6-L-11, section 10 ruling R-1b-1; E.3-L-15 and K4-L-01 adopted).

GENERATED by reports/stage_e8_briefs/gen_k6_tables.py from the frozen release calendar
reports/stage_e2b_release_calendar.json (sha256 below). Do not edit by hand:
tests/test_k6_members_tables.py recomputes the table from the calendar and asserts this file is
the generator's output.

WASDE_DATES: the CT dates (the row's instant_utc in America/Chicago) of every calendar row with
release "WASDE" at local time 12:00 America/New_York dated 2019-05-01..2026-06-19, less
DROPPED_WASDE. A row at another time would be left out, not re-timed, and listed (E.3-L-15).
The table spans both windows; Task 1b checked the 14 research-window rows (K4-L-01). The members
read the date only: T = 11:00 CT is fixed (C lines 72-74). is_wasde_date reads both tables at
call time.
"""

from __future__ import annotations

from datetime import date

# sha256 of the sources when the table was generated
SOURCE_SHA256: tuple[tuple[str, str], ...] = (
    ("reports/stage_e2b_release_calendar.json",
     "839f2437bedbeb7b3423d7058a9955a0d4ccd1aebc4b01c62be624ab11d7bcb8"),
    ("reports/stage_e8_release_check.json",
     "99547c142110cb5d4f6cf519ed488c98a5b78c4836d667dc292fe028d8f95c6b"),
)

WASDE_RANGE = ("2019-05-01", "2026-06-19")
WASDE_RELEASE_TIME = ("12:00", "America/New_York")

# WASDE rows of the range at a time other than 12:00 America/New_York (left out): none.
# Research-window rows (2025-04-01..2026-06-19): 14, each verdict keep in Task 1b's check. The
# cancelled October 2025 WASDE (scheduled 2025-10-09) has no row; the November 2025 WASDE moved
# from 2025-11-10 to 2025-11-14 by the NASS notice of 2025-10-31 and is kept (R-1b-1).

# R-1b-1 (spec section 10, lead 00:32 PDT): all 14 research-window rows kept; no row is
# dropped. ISO date -> reason for any dropped row.
DROPPED_WASDE: dict[date, str] = {}

# ISO CT dates of the 12:00 ET WASDE rows, oldest first (85 dates)
_WASDE_ISO: tuple[str, ...] = (
    "2019-05-10", "2019-06-11", "2019-07-11", "2019-08-12", "2019-09-12", "2019-10-10",
    "2019-11-08", "2019-12-10", "2020-01-10", "2020-02-11", "2020-03-10", "2020-04-09",
    "2020-05-12", "2020-06-11", "2020-07-10", "2020-08-12", "2020-09-11", "2020-10-09",
    "2020-11-10", "2020-12-10", "2021-01-12", "2021-02-09", "2021-03-09", "2021-04-09",
    "2021-05-12", "2021-06-10", "2021-07-12", "2021-08-12", "2021-09-10", "2021-10-12",
    "2021-11-09", "2021-12-09", "2022-01-12", "2022-02-09", "2022-03-09", "2022-04-08",
    "2022-05-12", "2022-06-10", "2022-07-12", "2022-08-12", "2022-09-12", "2022-10-12",
    "2022-11-09", "2022-12-09", "2023-01-12", "2023-02-08", "2023-03-08", "2023-04-11",
    "2023-05-12", "2023-06-09", "2023-07-12", "2023-08-11", "2023-09-12", "2023-10-12",
    "2023-11-09", "2023-12-08", "2024-01-12", "2024-02-08", "2024-03-08", "2024-04-11",
    "2024-05-10", "2024-06-12", "2024-07-12", "2024-08-12", "2024-09-12", "2024-10-11",
    "2024-11-08", "2024-12-10", "2025-01-10", "2025-02-11", "2025-03-11", "2025-04-10",
    "2025-05-12", "2025-06-12", "2025-07-11", "2025-08-12", "2025-09-12", "2025-11-14",
    "2025-12-09", "2026-01-12", "2026-02-10", "2026-03-10", "2026-04-09", "2026-05-12",
    "2026-06-11",
)

WASDE_DATES: frozenset[date] = frozenset(
    date.fromisoformat(s) for s in _WASDE_ISO) - frozenset(DROPPED_WASDE)


def is_wasde_date(d: date) -> bool:
    """d is an EC-WASDE date after C9a's drop rule (both tables read at call time)."""
    return d in WASDE_DATES and d not in DROPPED_WASDE


__all__ = ["DROPPED_WASDE", "WASDE_DATES", "is_wasde_date"]
