"""One-off generator of strategy/members/k2/_releases.py (Stage E.3 Task 2, MemberCoder-B).

Not imported by anything. Run from the repository root:
    uv run python reports/stage_e3_briefs/gen_k2_releases.py

It reads the frozen release calendar reports/stage_e2b_release_calendar.json, checks its sha256,
and writes the literal tables the K2 event members read (specs S0.11, L-01, L-02, L-14, L-15):
- TREASURY_AUCTIONS: (auction date, tenor, T_a "HH:MM" CT) for every TREASURY_AUCTION row whose id
  ends in -2Y, -5Y, -10Y or -30Y, T_a = the row's instant_utc in America/Chicago, less the entries
  of DROPPED_AUCTIONS (the lead's list from the C9 XML check);
- FOMC_STATEMENT_DATES: every FOMC row's date whose instant is 13:00 CT;
- ISM_SERVICES_DATES: every ISM_SERVICES row's date whose instant is 10:00 ET (09:00 CT).
It prints counts only, never the file.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

REPO = Path(__file__).resolve().parents[2]
CALENDAR = REPO / "reports" / "stage_e2b_release_calendar.json"
OUT = REPO / "strategy" / "members" / "k2" / "_releases.py"
EXPECTED_SHA256 = "839f2437bedbeb7b3423d7058a9955a0d4ccd1aebc4b01c62be624ab11d7bcb8"
CT = ZoneInfo("America/Chicago")
ET = ZoneInfo("America/New_York")
TENORS = ("2Y", "5Y", "10Y", "30Y")
FOMC_CT = "13:00"
ISM_ET = "10:00"

# The lead's list from reports/stage_e3_auction_xml_check.json: (date, tenor, reason). Empty until
# the lead sends it; each entry must be marked "disagree" there (the pin test checks it).
DROPPED: tuple[tuple[str, str, str], ...] = ()


def _local(instant_utc: str, tz: ZoneInfo) -> datetime:
    return datetime.fromisoformat(instant_utc.replace("Z", "+00:00")).astimezone(tz)


def build(raw: dict) -> tuple[list, list, list]:
    rows = raw["releases"]
    auctions = []
    for e in rows:
        if e["release"] != "TREASURY_AUCTION":
            continue
        tenor = e["id"].rsplit("-", 1)[1]
        if tenor not in TENORS:
            continue
        ct = _local(e["instant_utc"], CT)
        assert ct.date().isoformat() == e["date"], e["id"]
        auctions.append((e["date"], tenor, ct.strftime("%H:%M")))
    keys = [(d, t) for d, t, _ in auctions]
    assert len(keys) == len(set(keys)), "two auctions of one tenor on one date"
    dropped = {(d, t) for d, t, _ in DROPPED}
    assert dropped <= set(keys), "a dropped auction is not in the calendar"
    order = {t: i for i, t in enumerate(TENORS)}
    auctions = sorted((a for a in auctions if (a[0], a[1]) not in dropped),
                      key=lambda a: (a[0], order[a[1]]))
    fomc, ism = [], []
    for e in rows:
        if e["release"] == "FOMC":
            ct = _local(e["instant_utc"], CT)
            assert ct.date().isoformat() == e["date"], e["id"]
            if ct.strftime("%H:%M") == FOMC_CT:
                fomc.append(e["date"])
        elif e["release"] == "ISM_SERVICES":
            et = _local(e["instant_utc"], ET)
            assert et.date().isoformat() == e["date"], e["id"]
            if et.strftime("%H:%M") == ISM_ET:
                ism.append(e["date"])
    assert len(fomc) == len(set(fomc)) and len(ism) == len(set(ism))
    return auctions, sorted(fomc), sorted(ism)


def _rows(items: list, per_line: int) -> str:
    lines = []
    for i in range(0, len(items), per_line):
        lines.append("    " + " ".join(f"\"{x}\"," for x in items[i:i + per_line]))
    return "\n".join(lines)


def render(sha: str, auctions: list, fomc: list, ism: list) -> str:
    auction_items = [f'("{d}", "{t}", "{ta}")' for d, t, ta in auctions]
    dropped_items = [f'("{d}", "{t}", {r!r})' for d, t, r in DROPPED]
    auc_body = "\n".join("    " + " ".join(f"{x}," for x in auction_items[i:i + 3])
                         for i in range(0, len(auction_items), 3))
    drop_block = ("()" if not dropped_items
                  else "(\n" + "\n".join(f"    {x}," for x in dropped_items) + "\n)")
    counts = (f"{len(auctions)} auctions, {len(DROPPED)} dropped, {len(fomc)} FOMC dates, "
              f"{len(ism)} ISM dates")
    return f'''"""K2 event tables (Stage E.3; specs S0.11, L-01, L-02, L-14, L-15). GENERATED.

Generated by reports/stage_e3_briefs/gen_k2_releases.py from the frozen release calendar
reports/stage_e2b_release_calendar.json (sha256 RELEASE_CALENDAR_SHA256) and pinned by
tests/test_e3_k2_members_events.py, which recomputes every table from that file.

- TREASURY_AUCTIONS: (auction date, tenor, T_a) for every TREASURY_AUCTION row of tenor 2Y, 5Y,
  10Y or 30Y; T_a = the row's instant_utc in America/Chicago, "HH:MM" (= closing_time_comp ET
  - 1 h, L-14); the entries of DROPPED_AUCTIONS are left out (C9 XML check, L-02).
- DROPPED_AUCTIONS: (auction date, tenor, reason) dropped by the lead on the C9 XML check.
- FOMC_STATEMENT_DATES: the dates of the FOMC rows whose instant is 13:00 CT (L-15).
- ISM_SERVICES_DATES: the dates of the ISM_SERVICES rows whose instant is 10:00 ET = 09:00 CT
  (L-15).
Counts: {counts}.
Do not edit by hand: change the generator and run it again.
"""

from __future__ import annotations

RELEASE_CALENDAR_SHA256 = "{sha}"

DROPPED_AUCTIONS: tuple[tuple[str, str, str], ...] = {drop_block}

TREASURY_AUCTIONS: tuple[tuple[str, str, str], ...] = (
{auc_body}
)

FOMC_STATEMENT_DATES: tuple[str, ...] = (
{_rows(fomc, 6)}
)

ISM_SERVICES_DATES: tuple[str, ...] = (
{_rows(ism, 6)}
)
'''


def main() -> None:
    data = CALENDAR.read_bytes()
    sha = hashlib.sha256(data).hexdigest()
    assert sha == EXPECTED_SHA256, f"release calendar sha256 {sha} is not the frozen one"
    auctions, fomc, ism = build(json.loads(data))
    OUT.write_text(render(sha, auctions, fomc, ism), encoding="utf-8")
    per = {t: sum(1 for a in auctions if a[1] == t) for t in TENORS}
    times = sorted({a[2] for a in auctions})
    print(f"wrote {OUT.relative_to(REPO)}: auctions {len(auctions)} {per} T_a {times}; "
          f"dropped {len(DROPPED)}; FOMC {len(fomc)}; ISM {len(ism)}")


if __name__ == "__main__":
    main()
