"""One-off generator of strategy/members/k2/_month_end.py (Stage E.3, MemberCoder-A).

Not imported by anything. Run from the repository root:

    uv run python reports/stage_e3_briefs/gen_k2_month_end.py

It reads EC-CAL, the D10 rates calendar, through data.group_session.load_group_calendar("rates")
and writes the literal month-end table K2-monthend-01 trades (reports/stage_e3_member_specs.md
section 8, S0.11, L-16):

- N   = the last trade date of the calendar month (GroupCalendar.is_trade_date: a weekday that is
        not a FULL_CLOSURE holiday and not a booked-forward day; EARLY_HALT days ARE trade dates);
- N-1 = the calendar's trade date before N (data.group_session.previous_trade_date);
- a month enters the table only when its N lies inside the calendar's coverage
  (GroupCalendar.covers(N)); N-1 must then be covered too (asserted).

The table is also recomputed by tests/test_e3_k2_members.py, which asserts equality with the
written module (the pin), so the file and this script cannot drift apart silently.
"""

from __future__ import annotations

import sys
from datetime import date, timedelta
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from data.group_session import (  # noqa: E402
    load_group_calendar,
    previous_trade_date,
    sha256_file,
    trade_dates_between,
)

OUT = REPO_ROOT / "strategy" / "members" / "k2" / "_month_end.py"
CALENDAR_FILE = "data/calendars/rates.py"


def month_end_rows() -> list[tuple[str, str, str]]:
    """(YYYY-MM, N-1, N) for every calendar month whose N is covered, oldest first."""
    cal = load_group_calendar("rates")
    first, last = cal.coverage
    rows: list[tuple[str, str, str]] = []
    year, month = first.year, first.month
    while date(year, month, 1) <= last:
        start = date(year, month, 1)
        nxt = date(year + (month == 12), month % 12 + 1, 1)
        days = trade_dates_between(cal, start, nxt - timedelta(days=1))
        if days and cal.covers(days[-1]):
            n = days[-1]
            n1 = previous_trade_date(cal, n)
            assert n1 is not None and cal.covers(n1), (n, n1)
            rows.append((f"{year:04d}-{month:02d}", n1.isoformat(), n.isoformat()))
        year, month = nxt.year, nxt.month
    return rows


def render(rows: list[tuple[str, str, str]], sha: str) -> str:
    body = "\n".join(f'    ("{m}", "{a}", "{b}"),' for m, a, b in rows)
    return f'''"""K2-monthend-01 event dates: N-1 and N of each month (literal table; S0.11, L-16).

GENERATED by reports/stage_e3_briefs/gen_k2_month_end.py from EC-CAL, the D10 rates calendar
({CALENDAR_FILE}, read through data.group_session.load_group_calendar("rates")).
Do not edit by hand: tests/test_e3_k2_members.py recomputes the table from the calendar and
asserts equality.

N = the last trade date of the calendar month, N-1 = the calendar's trade date before N. The
calendar counts a weekday as a trade date unless it is a FULL_CLOSURE holiday (no booked-forward
days in the rates calendar); EARLY_HALT days are trade dates, each its own short trade date, so an
early-halt N or N-1 is listed here and dropped by the member at run time (C4), never moved.
Months whose N lies outside the calendar's coverage contribute no row (June 2026).
"""

from __future__ import annotations

MONTH_END_SOURCE = (
    "EC-CAL: data.group_session.load_group_calendar('rates') ({CALENDAR_FILE}); "
    "N = last trade date of the calendar month, N-1 = the trade date before N; "
    "months whose N lies inside the calendar coverage"
)
# sha256 of {CALENDAR_FILE} when the table was generated
MONTH_END_SOURCE_SHA256 = "{sha}"

# (calendar month "YYYY-MM", N-1 ISO date, N ISO date), oldest first
MONTH_END: tuple[tuple[str, str, str], ...] = (
{body}
)

__all__ = ["MONTH_END", "MONTH_END_SOURCE", "MONTH_END_SOURCE_SHA256"]
'''


def main() -> None:
    rows = month_end_rows()
    sha = sha256_file(REPO_ROOT / CALENDAR_FILE)
    OUT.write_text(render(rows, sha), encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}: {len(rows)} months, {rows[0][0]}..{rows[-1][0]}, "
          f"calendar sha256 {sha[:12]}")


if __name__ == "__main__":
    main()
